# DEEP LEARNING

**Deep learning (DL)**, a branch of machine learning (ML) and artifcial intelligence (AI) is nowadays considered as a core 
technology of today’s **Fourth Industrial Revolution (4IR or Industry 4.0)**. Due to its learning capabilities from data, DL 
technology originated from **artifcial neural network (ANN)**, has become a hot topic in the context of computing, and is 
widely applied in various application areas like healthcare, visual recognition, text analytics, cybersecurity, and many more. 

## ANN(Artificial Neural Network)

1. An Artificial Neural Network (ANN) is a computer system inspired by biological neural networks. It creates artificial brains using interconnected units called artificial neurons.
2. These networks are designed to analyze and process information in a manner similar to how humans do.
3. 

In [58]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [59]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [60]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [61]:
dataset.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [67]:
X = dataset.iloc[:  , 3:13].values
y = dataset.iloc[: , -1].values

In [68]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [72]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

**LabelEncoding(Converting the categorical data into numerical data)**

In [20]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[: , 2] = labelencoder.fit_transform(X[: , 2])

In [21]:
X[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers = [('encoder' , OneHotEncoder() , [1])] , remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [24]:
X = X[: , 1:] #avoid dummy variable trap

In [54]:
X[4]

array([0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1], dtype=object)

**Data Splitting (Training & Testing)**

In [53]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X, y, test_size = 0.2 , random_state = 0)

**Feature Scaling**

In [52]:
from sklearn.preprocessing import StandardScaler
sc=  StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

**Building a Neural Network**

In [30]:
import keras
from keras.models import Sequential
from keras.layers import Dense , Dropout

In [31]:
classifier = Sequential()

In [32]:
classifier.add(Dense(units = 15 , activation='relu' , kernel_initializer='glorot_uniform' , input_dim=11))

In [33]:
classifier.add(Dropout(rate=0.1))

In [37]:
classifier.add(Dense(units = 12 , activation='relu' , kernel_initializer='glorot_uniform'))
classifier.add(Dropout(rate=0.1))

In [38]:
classifier.add(Dense(units = 1 , activation='sigmoid'))

In [39]:
classifier.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [40]:
classifier.fit(x_train, y_train, batch_size=32 , epochs = 100)

Epoch 1/100


250/250 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7946
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4661 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4392 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4300 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4098 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4008 - accuracy: 0.8095
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8355
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3933 - accu

In [41]:
y_pred = classifier.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [42]:
y_pred

array([[0.31433415],
       [0.32771194],
       [0.11672144],
       ...,
       [0.1122825 ],
       [0.18390575],
       [0.17469847]], dtype=float32)

In [43]:
y_pred = y_pred >=0.5

In [48]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

**Confusion Matrix:**

In [47]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print("Confusion Matrix:\n",cm)
print("Accuracy:",accuracy_score(y_test , y_pred))

Confusion Matrix:
 [[1507   88]
 [ 184  221]]
Accuracy: 0.864


# Predicting a single new observation

Predict if the customer with the given information below will leave the bank or not:
1. Geography: Spain
2. Credit Score: 700
3. Gender: Female
4. Age: 35
5. Tenure: 4
6. Balance: 50000
7. Number of Products: 3
8. Has Credit Card: Yes
9. Is Active Member: Yes
10. Estimated Salary: 40000

In [49]:
y_new = classifier.predict(sc.transform(np.array([[0.0 , 1.0 , 700 , 0 ,35 , 4 ,50000 , 3 , 1 ,1 ,40000]])))

1/1 [==============================] - 0s 24ms/step


In [50]:
y_new

array([[0.76972824]], dtype=float32)

In [51]:
y_new = y_new>0.5
print(y_new)

[[ True]]
